import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { contentRepository } from "@/services/cms";
import { getPillarsForArticle } from "@/data/seo-pillars";
import { absoluteUrl, breadcrumbSchema } from "@/lib/seo";
import { formatFullDate, getRelativeTime, slugify } from "@/lib/content";
import { renderContentMarkup } from "@/lib/content-markup";
import { ArrowRight, Bookmark, Clock3 } from "@/components/ui/icons";
import { ArticleCard } from "@/components/editorial/article-card";
import styles from "./article.module.css";

export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const article=await contentRepository.getArticleBySlug(slug);if(!article)return{};const seo=article.seo,title=seo?.metaTitle||article.title,description=seo?.metaDescription||article.excerpt,image=seo?.ogImage||article.image;return{title,description,keywords:seo?.keywords,alternates:{canonical:seo?.canonical||`/noticias/${slug}`},openGraph:{type:"article",title,description,images:[image],publishedTime:article.publishedAt,authors:[article.author.name],tags:article.tags},twitter:{card:"summary_large_image",title,description,images:[image]}}}

export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const[article,articles]=await Promise.all([contentRepository.getArticleBySlug(slug),contentRepository.listArticles()]);if(!article)notFound();
  const related=articles.filter((item)=>item.slug!==article.slug&&(item.category===article.category||item.segments.some((segment)=>article.segments.includes(segment)))).slice(0,3);const pillars=getPillarsForArticle(article);
  const graph={"@context":"https://schema.org","@graph":[{"@type":article.seo?.schemaType??(article.type==="noticia"?"NewsArticle":"Article"),headline:article.title,description:article.excerpt,image:[absoluteUrl(article.seo?.ogImage||article.image)],datePublished:article.publishedAt,dateModified:article.updatedAt??article.publishedAt,author:{"@type":"Person",name:article.author.name,url:absoluteUrl(`/autores/${article.author.slug}`)},publisher:{"@type":"Organization",name:"VTRES60"},mainEntityOfPage:absoluteUrl(`/noticias/${article.slug}`)},...(article.faq?.length?[{"@type":"FAQPage",mainEntity:article.faq.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}]:[]),breadcrumbSchema([{name:"Início",url:"/"},{name:"Notícias",url:"/noticias"},{name:article.category,url:`/categorias/${article.categorySlug}`},{name:article.title,url:`/noticias/${article.slug}`}])]};
  return <main id="conteudo" className={styles.main}><article><header className={`container ${styles.header}`}><nav className={styles.breadcrumb} aria-label="Breadcrumb"><Link href="/">Início</Link><span>/</span><Link href="/noticias">Notícias</Link><span>/</span><Link href={`/categorias/${article.categorySlug}`}>{article.category}</Link></nav><div className={styles.label}><span>{article.category}</span><b>{article.educational?"artigo educativo":article.type}</b></div><h1>{article.title}</h1><p className={styles.deck}>{article.excerpt}</p><div className={styles.byline}><div><Link href={`/autores/${article.author.slug}`}><strong>{article.author.name}</strong><span>{article.author.role}</span></Link></div><time dateTime={article.publishedAt}><b>{getRelativeTime(article.publishedAt)}</b><span>{formatFullDate(article.publishedAt)}</span></time><small><Clock3 size={14}/>{article.readingTime} min de leitura</small><button aria-label="Salvar notícia"><Bookmark size={16}/></button></div></header><div className={`container ${styles.hero}`}><Image src={article.image} alt={article.imageAlt} fill priority sizes="(max-width:1300px) 100vw, 1280px"/></div>{article.imageCaption&&<p className={`container ${styles.caption}`}>{article.imageCaption}</p>}{article.imageCredit&&<p className={`container ${styles.caption}`}>{article.imageCredit}</p>}<div className={`container ${styles.layout}`}><aside><span>NESTE CONTEÚDO</span><a href="#contexto">Contexto</a>{article.impact&&<a href="#impacto">Impacto na indústria</a>}<a href="#decisao">Para sua empresa</a></aside><div className={styles.body}>{article.impact&&<div id="impacto" className={styles.impact}><span>O QUE ISSO MUDA PARA A INDÚSTRIA</span><strong>{article.impact.replace(/^(O impacto|A oportunidade):\s*/i,"")}</strong></div>}<div id="contexto" className={styles.richContent} dangerouslySetInnerHTML={{__html:renderContentMarkup(article.content??article.body.join("\n\n"))}}/>{article.cta&&<div id="decisao" className={styles.cta}><div><span>PRÓXIMA DECISÃO</span><strong>{article.cta.text}</strong></div><a href={article.cta.url}>{article.cta.label}<ArrowRight size={14}/></a></div>}{article.faq&&article.faq.length>0&&<section className={styles.faq}><span>PERGUNTAS FREQUENTES</span><h2>FAQ</h2>{article.faq.map(item=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>}{article.sourceName&&<p className={styles.source}>Fonte: {article.sourceUrl?<a href={article.sourceUrl} target="_blank" rel="noreferrer">{article.sourceName}</a>:article.sourceName}</p>}<footer>{article.tags.map((tag)=><Link href={`/tags/${slugify(tag)}`} key={tag}>#{tag}</Link>)}</footer></div>{article.companies[0]&&<aside className={styles.side}><div><span>EMPRESA CITADA</span><strong>{article.companies[0]}</strong><Link href={`/empresas/${slugify(article.companies[0])}`}>Abrir hub <ArrowRight size={12}/></Link></div></aside>}</div></article>
    <section className={styles.pillarLinks}><div className="container"><div className="section-head"><div><span className="eyebrow">Aprofunde a estratégia</span><h2 className="section-title">Guias de Marketing Industrial</h2></div><Link className="section-link" href="/categorias/marketing-industrial">Ver categoria →</Link></div><div className={styles.pillarGrid}>{pillars.slice(0,3).map((pillar)=><Link href={`/marketing-industrial/${pillar.slug}`} key={pillar.slug}><span>GUIA PILAR</span><h3>{pillar.title}</h3><p>{pillar.metaDescription}</p><b>Ler guia <ArrowRight size={12}/></b></Link>)}</div></div></section>
    {related.length>0&&<section className="section"><div className="container"><div className="section-head"><div><span className="eyebrow">Continue informado</span><h2 className="section-title">Leituras relacionadas</h2></div></div><div className={styles.related}>{related.map((item)=><ArticleCard article={item} key={item.slug}/>)}</div></div></section>}
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph)}}/>
  </main>
}
