import { NextResponse } from "next/server";import { requireAdmin } from "@/lib/admin-api";import { apiError } from "@/lib/editorial-api";import { validateEventPublication } from "@/lib/agenda/event-publish-rules";import { operationsRepository } from "@/services/operations";import type { ManagedEvent } from "@/types/operations";
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const denied=await requireAdmin();if(denied)return denied;const{id}=await params,item=await operationsRepository.getEvent(id);return item?NextResponse.json(item):apiError(new Error("Evento não encontrado."),404)}
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const denied=await requireAdmin();if(denied)return denied;try{const{id}=await params,patch=await request.json() as Partial<ManagedEvent>,current=await operationsRepository.getEvent(id) as ManagedEvent|undefined;if(!current)return apiError(new Error("Evento não encontrado."),404);
  // Fechamento Fase 8C (secao 8): servidor nunca confia no client — valida
  // o estado FINAL (atual + patch mesclado), nao so os campos enviados
  // nesta chamada, porque o client pode mandar so {status:"published"} e
  // depender de campos ja salvos antes.
  const merged={...current,...patch} as ManagedEvent;const publishErrors=validateEventPublication(merged,current);if(publishErrors.length)return apiError(new Error(publishErrors.map(e=>e.message).join(" ")),422);
  const item=await operationsRepository.updateEvent(id,patch);if(!item)return apiError(new Error("Evento não encontrado."),404);await operationsRepository.log("edição","eventos",`Evento “${item.name}” atualizado.`);return NextResponse.json(item)}catch(error){return apiError(error)}}
export async function DELETE(_:Request,{params}:{params:Promise<{id:string}>}){const denied=await requireAdmin();if(denied)return denied;const{id}=await params,item=await operationsRepository.getEvent(id);if(!item)return apiError(new Error("Evento não encontrado."),404);await operationsRepository.deleteEvent(id);await operationsRepository.log("exclusão","eventos",`Evento “${item.name}” excluído.`);return NextResponse.json({ok:true})}
