import type { Metadata } from "next";
import Link from "next/link";
import { contentRepository } from "@/services/cms";
import { editorialRepository } from "@/services/editorial";
import { absoluteUrl, breadcrumbSchema } from "@/lib/seo";
import { ArticleCard } from "@/components/editorial/article-card";
import { ArrowRight, Clock3 } from "@/components/ui/icons";
import styles from "./category.module.css";

export async function generateMetadata():Promise<Metadata>{const category=await editorialRepository.getCategory("marketing-industrial"),title=category?.metaTitle??"Marketing Industrial: Estratégias, Notícias e Guias",description=category?.page?.seoDescription??category?.metaDescription??"Estratégias, notícias e guias de marketing industrial.";return{title,description,keywords:category?.keywords,alternates:{canonical:"/categorias/marketing-industrial"},openGraph:{type:"website",title,description,url:"/categorias/marketing-industrial",images:category?.image?[category.image]:undefined},twitter:{card:"summary_large_image",title,description,images:category?.image?[category.image]:undefined}}}
export default async function MarketingIndustrialCategory(){
  const[category,articles,educational]=await Promise.all([editorialRepository.getCategory("marketing-industrial"),contentRepository.listArticles(),editorialRepository.listEducationalArticles()]);if(!category)return null;const page=category.page;
  const marketingArticles=articles.filter(article=>article.categorySlug==="marketing-industrial"&&!article.educational);const configuredNews=page?.newsSlugs.map(slug=>marketingArticles.find(article=>article.slug===slug)).filter((item):item is NonNullable<typeof item>=>Boolean(item))??[];const marketingNews=[...configuredNews,...marketingArticles.filter(article=>!configuredNews.some(item=>item.slug===article.slug))].slice(0,Math.max(3,configuredNews.length));
  const publishedEducational=educational.filter(item=>item.status==="published"&&item.categoryId===category.id);const configuredGuides=page?.educationalArticleSlugs.map(slug=>publishedEducational.find(item=>item.slug===slug)).filter((item):item is NonNullable<typeof item>=>Boolean(item))??[];const guides=[...configuredGuides,...publishedEducational.filter(item=>!configuredGuides.some(guide=>guide.slug===item.slug))];
  const graph={"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","@id":`${absoluteUrl("/categorias/marketing-industrial")}#collection`,name:page?.h1??category.name,description:page?.seoDescription??category.metaDescription,url:absoluteUrl("/categorias/marketing-industrial"),hasPart:[...marketingNews.map(item=>({"@type":"NewsArticle",name:item.title,url:absoluteUrl(`/noticias/${item.slug}`)})),...guides.map(item=>({"@type":"Article",name:item.title,url:absoluteUrl(`/noticias/${item.slug}`)}))]},{"@type":"ItemList",name:"Notícias sobre Marketing Industrial",itemListElement:marketingNews.map((article,index)=>({"@type":"ListItem",position:index+1,url:absoluteUrl(`/noticias/${article.slug}`),name:article.title}))},...(page?.faq?.length?[{"@type":"FAQPage",mainEntity:page.faq.map(item=>({"@type":"Question",name:item.question,acceptedAnswer:{"@type":"Answer",text:item.answer}}))}]:[]),breadcrumbSchema([{name:"Início",url:"/"},{name:"Categorias",url:"/categorias"},{name:category.name,url:"/categorias/marketing-industrial"}])]};
  return <main id="conteudo" className={styles.main}><header className={styles.hero}><div className="container"><nav aria-label="Breadcrumb"><Link href="/">Início</Link><span>/</span><Link href="/categorias">Categorias</Link><span>/</span><b>{category.name}</b></nav><span className="eyebrow">Categoria principal</span><h1>{page?.h1??category.name}</h1><p>{page?.introduction??category.seoIntroduction}</p></div></header><section className={styles.news}><div className="container"><div className="section-head"><div><span className="eyebrow">Atualização editorial</span><h2 className="section-title">Notícias sobre Marketing Industrial</h2></div><Link className="section-link" href="/noticias">Ver todas as notícias →</Link></div><div className={styles.newsGrid}>{marketingNews.map((article,index)=><ArticleCard article={article} key={article.slug} priority={index===0}/>)}</div></div></section><section className={styles.guides}><div className="container"><div className="section-head"><div><span className="eyebrow">Conteúdo evergreen</span><h2 className="section-title">Guias e insights para marketing industrial</h2></div></div><p className={styles.guidesIntro}>{category.seoIntroduction}</p><div className={styles.guidesGrid}>{guides.map((guide,index)=><Link href={`/noticias/${guide.slug}`} key={guide.id}><header><span>GUIA {String(index+1).padStart(2,"0")}</span><small><Clock3 size={11}/>{guide.readingTime} min</small></header><h3>{guide.title}</h3><p>{guide.excerpt}</p><div><b>PALAVRA-CHAVE</b><span>{guide.primaryKeyword}</span></div><footer>Explorar guia<ArrowRight size={13}/></footer></Link>)}</div></div></section>{page?.faq&&page.faq.length>0&&<section className={styles.faq}><div className="container"><span className="eyebrow">Perguntas frequentes</span><h2>Marketing Industrial na prática</h2>{page.faq.map(item=><details key={item.question}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section>}<section className={styles.cta}><div className="container"><div><span>VTRES60</span><h2>{page?.cta.text??"Posicione sua indústria para ser encontrada, lembrada e escolhida."}</h2></div><a href={page?.cta.url??"mailto:especialista@vtres60.com.br"}>{page?.cta.label??"Falar com especialista"}<ArrowRight size={15}/></a></div></section><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph)}}/></main>
}
