import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { contentRepository } from "@/services/cms";
import { absoluteUrl, breadcrumbSchema } from "@/lib/seo";
import { ArrowRight, CalendarDays, Building2 } from "@/components/ui/icons";
import styles from "./event.module.css";

// Fase 8C — rotulos honestos por dataStatus (secao 4: nunca chamar
// evento nao verificado de confirmado). "unverified" e o estado de quem
// nunca deveria estar publicado (listEvents ja filtra isso), mas o rotulo
// existe para o preview/admin tambem usarem este mesmo mapa.
const DATA_STATUS_LABEL:Record<string,string>={official_verified:"DADOS VERIFICADOS NA FONTE OFICIAL",manual_verified:"DADOS VERIFICADOS MANUALMENTE",unverified:"DADOS AINDA NÃO VERIFICADOS"};

export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const{slug}=await params;const events=await contentRepository.listEvents();const event=events.find((item)=>item.slug===slug);if(!event)return{};const title=`${event.title}: data, local e oportunidades`,description=`Informações sobre ${event.title}, em ${event.location}: segmento, público, expositores e oportunidades para empresas industriais.`;return{title,description,alternates:{canonical:`/agenda/${event.slug}`},openGraph:{type:"website",title,description,url:`/agenda/${event.slug}`,images:[event.image]},twitter:{card:"summary_large_image",title,description,images:[event.image]}}}

export default async function EventPage({params}:{params:Promise<{slug:string}>}){
  const{slug}=await params;const events=await contentRepository.listEvents();const event=events.find((item)=>item.slug===slug);if(!event)notFound();const configured=event.relatedEventIds?.map(id=>events.find(item=>item.id===id)).filter((item):item is NonNullable<typeof item>=>Boolean(item))??[];const related=[...configured,...events.filter(item=>item.slug!==event.slug&&!configured.some(selected=>selected.slug===item.slug))].slice(0,3);
  const graph={"@context":"https://schema.org","@graph":[{"@type":"Event",name:event.title,description:event.description,image:[absoluteUrl(event.image)],startDate:event.startDate,endDate:event.endDate,eventStatus:"https://schema.org/EventScheduled",eventAttendanceMode:"https://schema.org/OfflineEventAttendanceMode",location:{"@type":"Place",name:event.venue,address:{"@type":"PostalAddress",streetAddress:event.address,addressLocality:event.city,addressRegion:event.state,addressCountry:"BR"}},organizer:{"@type":"Organization",name:"Organização do evento",url:event.ctaUrl},url:absoluteUrl(`/agenda/${event.slug}`)},breadcrumbSchema([{name:"Início",url:"/"},{name:"Agenda Industrial",url:"/agenda"},{name:event.title,url:`/agenda/${event.slug}`}])]};
  return <main id="conteudo" className={styles.main}><header className={styles.hero}><div className="container"><nav aria-label="Breadcrumb"><Link href="/">Início</Link><span>/</span><Link href="/agenda">Agenda Industrial</Link><span>/</span><b>{event.title}</b></nav><div className={styles.heroGrid}><div><span className="eyebrow">Agenda Industrial</span><div className={styles.status}>{DATA_STATUS_LABEL[event.dataStatus]??"DADOS AINDA NÃO VERIFICADOS"}</div><h1>{event.title}</h1><p>{event.description}</p><div className={styles.heroMeta}><span><CalendarDays size={15}/>{event.date} {event.month}</span><span>{event.location}</span><span>{event.segment}</span></div></div><div className={styles.heroImage}><Image src={event.image} alt={event.imageAlt} fill priority sizes="(max-width:800px) 100vw, 45vw"/></div></div></div></header>
    <section className={styles.facts}><div className="container"><div><span>LOCAL</span><strong>{event.venue}</strong><p>{event.address}</p></div><div><span>PÚBLICO ESPERADO</span><strong>{event.expectedAudience}</strong><p>Estimativa demonstrativa</p></div><div><span>EXPOSITORES</span><strong>{event.exhibitors}</strong><p>Estimativa demonstrativa</p></div><div><span>SEGMENTO</span><strong>{event.segment}</strong></div></div></section>
    <section className={styles.content}><div className="container"><article><span className="eyebrow">Leitura editorial</span><h2>Por que acompanhar {event.title}?</h2><p>{event.description} Para líderes industriais, acompanhar esse movimento ajuda a identificar prioridades de investimento, parceiros e sinais de demanda.</p><ul>{event.whyFollow.map((item)=><li key={item}>{item}</li>)}</ul></article><aside><Building2 size={22}/><span>OPORTUNIDADES PARA EMPRESAS INDUSTRIAIS</span>{event.opportunities.map((item,index)=><div key={item}><b>0{index+1}</b><p>{item}</p></div>)}<a href={event.ctaUrl} target="_blank" rel="noreferrer">{event.ctaLabel??"Visitar site do evento"} <ArrowRight size={14}/></a></aside></div></section>
    {Boolean(event.additionalImages?.length)&&<section className={styles.gallery}><div className="container"><span className="eyebrow">Galeria do evento</span><h2>Imagens e contexto visual</h2><div>{event.additionalImages?.map((image,index)=><figure key={`${image}-${index}`}><Image src={image} alt={`${event.title}: imagem ${index+1}`} fill sizes="(max-width:700px) 100vw, 33vw"/></figure>)}</div></div></section>}
    <section className={styles.related}><div className="container"><div className="section-head"><div><span className="eyebrow">Continue planejando</span><h2 className="section-title">Eventos relacionados</h2></div><Link className="section-link" href="/agenda">Agenda completa →</Link></div><div className={styles.relatedGrid}>{related.map((item)=><Link href={`/agenda/${item.slug}`} key={item.slug}><div><Image src={item.image} alt={item.imageAlt} fill sizes="(max-width:700px) 100vw, 50vw"/></div><span>{item.date} {item.month} · {item.location}</span><h3>{item.title}</h3><b>Ver evento <ArrowRight size={12}/></b></Link>)}</div></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph)}}/>
  </main>
}
