"use client";
import { withBasePath } from "@/lib/paths";
import Image from "next/image";
import type { BrandingSettings } from "@/types/admin";
import { useConfigEditor } from "./use-config-editor";
import { SaveBar } from "./save-bar";

const assets:[keyof Pick<BrandingSettings,"logoPrimary"|"logoDark"|"favicon"|"compactMark"|"defaultShareImage">,string][]=[
  ["logoPrimary","Logo principal"],["logoDark","Logo para fundo escuro"],["favicon","Favicon"],["compactMark","Símbolo reduzido"],["defaultShareImage","Imagem padrão de compartilhamento"]
];
const colorLabels:Record<keyof BrandingSettings["colors"],string>={primary:"Cor primária",secondary:"Cor secundária",accent:"Cor de destaque",lightBackground:"Fundo claro",darkBackground:"Fundo escuro",button:"Cor dos botões",link:"Cor dos links"};

export function BrandingForm({initial}:{initial:BrandingSettings}){
  const{data,setData,state,message,save}=useConfigEditor(initial,"/api/admin/branding");
  async function upload(key:typeof assets[number][0],file?:File){if(!file)return;const form=new FormData();form.append("file",file);const response=await fetch(withBasePath("/api/admin/uploads"),{method:"POST",body:form});const body=await response.json();if(!response.ok){alert(body.error||"Falha no upload");return}setData({...data,[key]:body.url})}
  return <div className="admin-form"><details className="admin-section" open><summary>Arquivos da marca</summary><div className="admin-section-body"><p className="admin-help">As imagens são armazenadas em <b>/public/uploads</b>. O preview é imediato; clique em “Salvar alterações” para publicar o novo caminho no portal.</p><div className="admin-assets">{assets.map(([key,label])=><article className="admin-asset" key={key}><span className="admin-label">{label}</span><div className="admin-asset-preview">{data[key]?<Image src={data[key]} alt={`Preview: ${label}`} width={260} height={90} unoptimized/>:<small>Nenhuma imagem enviada</small>}</div><footer><label>Selecionar arquivo<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml,image/x-icon" onChange={(e)=>upload(key,e.target.files?.[0])}/></label></footer><div className="admin-field" style={{marginTop:10}}><input aria-label={`Caminho: ${label}`} value={data[key]} onChange={(e)=>setData({...data,[key]:e.target.value})} placeholder="/uploads/arquivo.png"/></div></article>)}</div></div></details><details className="admin-section" open><summary>Paleta de cores</summary><div className="admin-section-body"><div className="admin-fields">{(Object.keys(colorLabels) as Array<keyof BrandingSettings["colors"]>).map((key)=><div className="admin-field" key={key}><label>{colorLabels[key]}</label><div className="admin-color"><input type="color" value={data.colors[key]} onChange={(e)=>setData({...data,colors:{...data.colors,[key]:e.target.value}})}/><input value={data.colors[key]} onChange={(e)=>setData({...data,colors:{...data.colors,[key]:e.target.value}})}/></div></div>)}</div></div></details><details className="admin-section"><summary>Tipografia e componentes</summary><div className="admin-section-body"><div className="admin-fields"><div className="admin-field"><label>Tipografia principal</label><input value={data.typography.body} onChange={(e)=>setData({...data,typography:{...data.typography,body:e.target.value}})}/></div><div className="admin-field"><label>Tipografia de títulos</label><input value={data.typography.headings} onChange={(e)=>setData({...data,typography:{...data.typography,headings:e.target.value}})}/></div><div className="admin-field"><label>Raio dos cards (px)</label><input type="number" min="0" max="40" value={data.cardRadius} onChange={(e)=>setData({...data,cardRadius:Number(e.target.value)})}/></div><div className="admin-field"><label>Intensidade de sombra</label><select value={data.shadowIntensity} onChange={(e)=>setData({...data,shadowIntensity:e.target.value as BrandingSettings["shadowIntensity"]})}><option value="soft">Suave</option><option value="medium">Média</option><option value="strong">Intensa</option></select></div></div></div></details><SaveBar state={state} message={message} onSave={save}/></div>
}


