"use client";
import Link from "next/link";
import { Copy, FilePlus2, Pencil, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";

export interface CrudListItem { id:string;title:string;slug:string;meta:string;status?:string }
export function CrudList({initial,basePath,apiPath,createLabel,entityName,feminine=false,allowDuplicate=false}:{initial:CrudListItem[];basePath:string;apiPath:string;createLabel:string;entityName:string;feminine?:boolean;allowDuplicate?:boolean}){
  const[items,setItems]=useState(initial);const[query,setQuery]=useState("");const[status,setStatus]=useState("all");const[feedback,setFeedback]=useState<{text:string;error:boolean}|null>(null);const[loadingId,setLoadingId]=useState("");
  const visible=useMemo(()=>items.filter((item)=>(!query||`${item.title} ${item.slug} ${item.meta}`.toLowerCase().includes(query.toLowerCase()))&&(status==="all"||item.status===status)),[items,query,status]);
  async function remove(item:CrudListItem){if(!window.confirm(`Excluir ${entityName.toLowerCase()} “${item.title}”? Esta ação não pode ser desfeita.`))return;setLoadingId(item.id);setFeedback(null);const response=await fetch(`${apiPath}/${item.id}`,{method:"DELETE"});const body=await response.json();if(!response.ok){setFeedback({text:body.error||"Falha ao excluir.",error:true})}else{setItems((current)=>current.filter((record)=>record.id!==item.id));setFeedback({text:`${entityName} ${feminine?"excluída":"excluído"} com sucesso.`,error:false})}setLoadingId("")}
  async function duplicate(item:CrudListItem){setLoadingId(item.id);setFeedback(null);const response=await fetch(`${apiPath}/${item.id}/duplicate`,{method:"POST"});const body=await response.json();if(!response.ok)setFeedback({text:body.error||"Falha ao duplicar.",error:true});else{setItems((current)=>[{id:body.id,title:body.title,slug:body.slug,meta:item.meta,status:body.status},...current]);setFeedback({text:`${entityName} ${feminine?"duplicada":"duplicado"} como rascunho.`,error:false})}setLoadingId("")}
  return <><div className="admin-toolbar"><div className="admin-toolbar-search"><Search size={15}/><input aria-label={`Buscar ${entityName.toLowerCase()}`} value={query} onChange={(event)=>setQuery(event.target.value)} placeholder={`Buscar por título, slug ou contexto...`}/></div>{items.some((item)=>item.status)&&<select aria-label="Filtrar por status" value={status} onChange={(event)=>setStatus(event.target.value)}><option value="all">Todos os status</option><option value="published">Publicados</option><option value="draft">Rascunhos</option><option value="scheduled">Agendados</option></select>}<Link className="admin-primary-button" href={`${basePath}/${basePath.endsWith("categorias")?"nova":"novo"}`}><FilePlus2 size={14}/>{createLabel}</Link></div>{feedback&&<div className="admin-feedback" data-error={feedback.error}>{feedback.text}</div>}<section className="admin-table"><div className="admin-table-head"><span>Conteúdo</span><span>Contexto</span><span>Status</span><span>Ações</span></div>{visible.map((item)=><article className="admin-table-row" key={item.id} aria-busy={loadingId===item.id}><div className="admin-table-title"><b>{item.title}</b><small>/{item.slug}</small></div><span className="admin-table-meta">{item.meta}</span>{item.status?<span className="admin-status" data-status={item.status}>{statusLabel(item.status)}</span>:<span className="admin-status">Ativo</span>}<div className="admin-row-actions"><Link href={`${basePath}/${item.id}`} aria-label={`Editar ${item.title}`}><Pencil size={13}/></Link>{allowDuplicate&&<button onClick={()=>duplicate(item)} aria-label={`Duplicar ${item.title}`} disabled={loadingId===item.id}><Copy size={13}/></button>}<button className="danger" onClick={()=>remove(item)} aria-label={`Excluir ${item.title}`} disabled={loadingId===item.id}><Trash2 size={13}/></button></div></article>)}{visible.length===0&&<div className="admin-empty"><FilePlus2 size={28}/><h2>Nenhum resultado</h2><p>{items.length?"Ajuste a busca ou o filtro para encontrar outros registros.":`Crie o primeiro ${entityName.toLowerCase()} para começar.`}</p></div>}</section></>
}
// Fase 8C — statusLabel tambem cobre o ciclo de vida de eventos da
// Agenda (candidate/verified/published/archived/cancelled), alem dos
// status de posts editoriais (published/scheduled/draft) ja existentes.
const statusLabel=(status:string)=>({published:"Publicado",scheduled:"Agendado",candidate:"Candidato",verified:"Verificado",archived:"Arquivado",cancelled:"Cancelado"}[status]??"Rascunho");
