"use client";
import { useEffect, useId } from "react";
import type { HomeSettings, NavigationLink } from "@/types/admin";
import { useConfigEditor } from "./use-config-editor";
import { SaveBar } from "./save-bar";

export function HomeForm({initial}:{initial:HomeSettings}){
  const{data,setData,state,message,save}=useConfigEditor(initial,"/api/admin/home");
  useEffect(()=>{const id=window.location.hash.slice(1);if(!id)return;const target=document.getElementById(id) as HTMLDetailsElement|null;if(target){target.open=true;target.scrollIntoView({behavior:"smooth",block:"start"})}},[]);
  return <div className="admin-form">
    <details className="admin-section" id="hero" open><summary>Hero</summary><div className="admin-section-body"><div className="admin-fields"><Toggle label="Exibir Hero" checked={data.hero.enabled} onChange={(v)=>setData({...data,hero:{...data.hero,enabled:v}})}/><Toggle label="Exibir subtítulo" checked={data.hero.showSubtitle} onChange={(v)=>setData({...data,hero:{...data.hero,showSubtitle:v}})}/><Field label="Título principal" value={data.hero.title} onChange={(v)=>setData({...data,hero:{...data.hero,title:v}})}/><Field label="Trecho em destaque" value={data.hero.highlightedText} onChange={(v)=>setData({...data,hero:{...data.hero,highlightedText:v}})}/><Field full label="Subtítulo" value={data.hero.subtitle} onChange={(v)=>setData({...data,hero:{...data.hero,subtitle:v}})}/><LinkFields title="Botão principal" value={data.hero.primaryButton} onChange={(primaryButton)=>setData({...data,hero:{...data.hero,primaryButton}})}/><LinkFields title="Botão secundário" value={data.hero.secondaryButton} onChange={(secondaryButton)=>setData({...data,hero:{...data.hero,secondaryButton}})}/><Field full label="Placeholder da busca" value={data.hero.searchPlaceholder} onChange={(v)=>setData({...data,hero:{...data.hero,searchPlaceholder:v}})}/><Field label="Elemento visual" value={data.hero.visual} onChange={(v)=>setData({...data,hero:{...data.hero,visual:v}})}/><Field label="Cor de fundo" type="color" value={data.hero.background} onChange={(v)=>setData({...data,hero:{...data.hero,background:v}})}/><Field label="Cor do texto" type="color" value={data.hero.textColor} onChange={(v)=>setData({...data,hero:{...data.hero,textColor:v}})}/><div className="admin-field admin-field-full"><div className="admin-array-row"><Toggle label="Exibir busca" checked={data.hero.showSearch} onChange={(v)=>setData({...data,hero:{...data.hero,showSearch:v}})}/><Toggle label="Exibir botão principal" checked={data.hero.showPrimaryButton} onChange={(v)=>setData({...data,hero:{...data.hero,showPrimaryButton:v}})}/><Toggle label="Exibir botão secundário" checked={data.hero.showSecondaryButton} onChange={(v)=>setData({...data,hero:{...data.hero,showSecondaryButton:v}})}/></div></div></div></div></details>
    <details className="admin-section" id="destaque-editorial" open><summary>Destaque Editorial</summary><div className="admin-section-body"><div className="admin-fields"><Toggle label="Exibir seção" checked={data.featured.enabled} onChange={(v)=>setData({...data,featured:{...data.featured,enabled:v}})}/><Field label="Eyebrow" value={data.featured.eyebrow} onChange={(v)=>setData({...data,featured:{...data.featured,eyebrow:v}})}/><Field label="Título da seção" value={data.featured.title} onChange={(v)=>setData({...data,featured:{...data.featured,title:v}})}/><Field label="Subtítulo" value={data.featured.subtitle} onChange={(v)=>setData({...data,featured:{...data.featured,subtitle:v}})}/><Field label="Slug da notícia principal" value={data.featured.leadArticleSlug} onChange={(v)=>setData({...data,featured:{...data.featured,leadArticleSlug:v}})} hint="Vazio mantém a seleção editorial padrão."/><Field label="Slugs das notícias laterais" value={data.featured.sideArticleSlugs.join(", ")} onChange={(v)=>setData({...data,featured:{...data.featured,sideArticleSlugs:split(v)}})} hint="Separe por vírgulas."/><LinkFields title="Botão da seção" value={data.featured.button} onChange={(button)=>setData({...data,featured:{...data.featured,button}})}/></div></div></details>
    <details className="admin-section" id="ultimas-noticias"><summary>Agora no Portal / Últimas Notícias</summary><div className="admin-section-body"><div className="admin-fields"><Toggle label="Exibir seção" checked={data.latest.enabled} onChange={(v)=>setData({...data,latest:{...data.latest,enabled:v}})}/><Field label="Eyebrow" value={data.latest.eyebrow} onChange={(v)=>setData({...data,latest:{...data.latest,eyebrow:v}})}/><Field label="Título" value={data.latest.title} onChange={(v)=>setData({...data,latest:{...data.latest,title:v}})}/><Field label="Subtítulo" value={data.latest.subtitle} onChange={(v)=>setData({...data,latest:{...data.latest,subtitle:v}})}/><NumberField label="Quantidade de posts" value={data.latest.postCount} min={1} max={12} onChange={(v)=>setData({...data,latest:{...data.latest,postCount:v}})}/><Field label="Filtro por categoria" value={data.latest.categoryFilter} onChange={(v)=>setData({...data,latest:{...data.latest,categoryFilter:v}})} hint="Use o slug; vazio mostra todas."/><Select label="Ordem" value={data.latest.order} options={[["newest","Mais recentes"],["oldest","Mais antigas"],["popular","Mais lidas"]]} onChange={(v)=>setData({...data,latest:{...data.latest,order:v as HomeSettings["latest"]["order"]}})}/><Select label="Layout" value={data.latest.layout} options={[["editorial","Editorial"],["grid","Grade"]]} onChange={(v)=>setData({...data,latest:{...data.latest,layout:v as HomeSettings["latest"]["layout"]}})}/></div></div></details>
    <details className="admin-section" id="segmentos"><summary>Segmentos Industriais</summary><div className="admin-section-body"><div className="admin-fields"><Toggle label="Exibir seção" checked={data.segments.enabled} onChange={(v)=>setData({...data,segments:{...data.segments,enabled:v}})}/><Field label="Eyebrow" value={data.segments.eyebrow} onChange={(v)=>setData({...data,segments:{...data.segments,eyebrow:v}})}/><Field label="Título" value={data.segments.title} onChange={(v)=>setData({...data,segments:{...data.segments,title:v}})}/><Field label="Subtítulo" value={data.segments.subtitle} onChange={(v)=>setData({...data,segments:{...data.segments,subtitle:v}})}/><Field full label="Ordem dos segmentos" value={data.segments.order.join(", ")} onChange={(v)=>setData({...data,segments:{...data.segments,order:split(v)}})} hint="Informe os slugs separados por vírgulas."/><Select label="Fundo" value={data.segments.theme} options={[["dark","Escuro"],["light","Claro"]]} onChange={(v)=>setData({...data,segments:{...data.segments,theme:v as "dark"|"light"}})}/></div></div></details>
    <details className="admin-section" id="agenda"><summary>Agenda Industrial</summary><div className="admin-section-body"><div className="admin-fields"><Toggle label="Exibir seção" checked={data.agenda.enabled} onChange={(v)=>setData({...data,agenda:{...data.agenda,enabled:v}})}/><Field label="Eyebrow" value={data.agenda.eyebrow} onChange={(v)=>setData({...data,agenda:{...data.agenda,eyebrow:v}})}/><Field label="Título" value={data.agenda.title} onChange={(v)=>setData({...data,agenda:{...data.agenda,title:v}})}/><Field label="Subtítulo" value={data.agenda.subtitle} onChange={(v)=>setData({...data,agenda:{...data.agenda,subtitle:v}})}/><NumberField label="Quantidade de eventos" value={data.agenda.eventCount} min={1} max={12} onChange={(v)=>setData({...data,agenda:{...data.agenda,eventCount:v}})}/><LinkFields title="CTA da Agenda" value={data.agenda.cta} onChange={(cta)=>setData({...data,agenda:{...data.agenda,cta}})}/></div></div></details>
    <details className="admin-section" id="newsletter"><summary>Newsletter</summary><div className="admin-section-body"><div className="admin-fields"><Toggle label="Exibir seção" checked={data.newsletter.enabled} onChange={(v)=>setData({...data,newsletter:{...data.newsletter,enabled:v}})}/><Field label="Eyebrow" value={data.newsletter.eyebrow} onChange={(v)=>setData({...data,newsletter:{...data.newsletter,eyebrow:v}})}/><Field full label="Título" value={data.newsletter.title} onChange={(v)=>setData({...data,newsletter:{...data.newsletter,title:v}})}/><Field full textarea label="Descrição" value={data.newsletter.description} onChange={(v)=>setData({...data,newsletter:{...data.newsletter,description:v}})}/><Field full label="Benefícios" value={data.newsletter.benefits.join(", ")} onChange={(v)=>setData({...data,newsletter:{...data.newsletter,benefits:split(v)}})} hint="Separe por vírgulas."/>{data.newsletter.fields.map((field,index)=><div className="admin-field admin-field-full" key={`${field.name}-${index}`}><label>Campo do formulário</label><div className="admin-array-row"><input aria-label="Label do campo" value={field.label} onChange={(e)=>setData({...data,newsletter:{...data.newsletter,fields:data.newsletter.fields.map((f,i)=>i===index?{...f,label:e.target.value}:f)}})}/><input aria-label="Placeholder do campo" value={field.placeholder} onChange={(e)=>setData({...data,newsletter:{...data.newsletter,fields:data.newsletter.fields.map((f,i)=>i===index?{...f,placeholder:e.target.value}:f)}})}/><label className="admin-check"><input type="checkbox" checked={field.required} onChange={(e)=>setData({...data,newsletter:{...data.newsletter,fields:data.newsletter.fields.map((f,i)=>i===index?{...f,required:e.target.checked}:f)}})}/>Obrigatório</label></div></div>)}<Field label="Texto do botão" value={data.newsletter.buttonText} onChange={(v)=>setData({...data,newsletter:{...data.newsletter,buttonText:v}})}/><Field label="Mensagem de sucesso" value={data.newsletter.successMessage} onChange={(v)=>setData({...data,newsletter:{...data.newsletter,successMessage:v}})}/></div></div></details>
    <details className="admin-section"><summary>Visibilidade das demais seções</summary><div className="admin-section-body"><div className="admin-fields">{([["radar","Radar Industrial"],["segmentFilter","Filtro por segmento"],["intelligence","Inteligência VTRES60"],["analysis","Análise VTRES60"],["companies","Empresas acompanhadas"],["market","Mercado e clima"]] as const).map(([key,label])=><Toggle key={key} label={label} checked={data.modules[key]} onChange={(v)=>setData({...data,modules:{...data.modules,[key]:v}})}/>)}</div></div></details>
    <SaveBar state={state} message={message} onSave={save}/>
  </div>
}

const split=(value:string)=>value.split(",").map((item)=>item.trim()).filter(Boolean);
function Field({label,value,onChange,type="text",textarea=false,full=false,hint}:{label:string;value:string;onChange:(value:string)=>void;type?:string;textarea?:boolean;full?:boolean;hint?:string}){const id=useId();return <div className={`admin-field ${full?"admin-field-full":""}`}><label htmlFor={id}>{label}</label>{textarea?<textarea id={id} value={value} onChange={(e)=>onChange(e.target.value)}/>:<input id={id} type={type} value={value} onChange={(e)=>onChange(e.target.value)}/>} {hint&&<small>{hint}</small>}</div>}
function NumberField({label,value,onChange,min,max}:{label:string;value:number;onChange:(value:number)=>void;min:number;max:number}){const id=useId();return <div className="admin-field"><label htmlFor={id}>{label}</label><input id={id} type="number" min={min} max={max} value={value} onChange={(e)=>onChange(Number(e.target.value))}/></div>}
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(checked:boolean)=>void}){return <label className="admin-check"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/>{label}</label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[][];onChange:(value:string)=>void}){const id=useId();return <div className="admin-field"><label htmlFor={id}>{label}</label><select id={id} value={value} onChange={(e)=>onChange(e.target.value)}>{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></div>}
function LinkFields({title,value,onChange}:{title:string;value:NavigationLink;onChange:(value:NavigationLink)=>void}){const labelId=useId(),urlId=useId();return <><div className="admin-field"><label htmlFor={labelId}>{title}: texto</label><input id={labelId} value={value.label} onChange={(e)=>onChange({...value,label:e.target.value})}/></div><div className="admin-field"><label htmlFor={urlId}>{title}: link</label><input id={urlId} value={value.url} onChange={(e)=>onChange({...value,url:e.target.value})}/></div></>}
