"use client";
import { withBasePath } from "@/lib/paths";
import Image from "next/image";
import { Clipboard, ImagePlus, Pencil, Search, Trash2, Upload } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import type { MediaAsset, MediaType } from "@/types/operations";

const types:[MediaType,string][]=[["general","Imagens gerais"],["logos","Logos"],["news","Notícias"],["articles","Artigos"],["events","Eventos"],["segments","Segmentos"],["open-graph","Open Graph"]];
export function MediaLibrary({initial}:{initial:MediaAsset[]}){
  const[items,setItems]=useState(initial),[query,setQuery]=useState(""),[type,setType]=useState<MediaType|"all">("all"),[feedback,setFeedback]=useState(""),[uploading,setUploading]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
  const visible=useMemo(()=>items.filter(item=>(type==="all"||item.type===type)&&(!query||`${item.filename} ${item.altText}`.toLowerCase().includes(query.toLowerCase()))),[items,query,type]);
  async function upload(file?:File){if(!file)return;setUploading(true);setFeedback("");const form=new FormData();form.append("file",file);form.append("type",type==="all"?"general":type);const response=await fetch(withBasePath("/api/admin/uploads"),{method:"POST",body:form}),body=await response.json();if(response.ok){setItems(current=>[body,...current]);setFeedback("Imagem enviada para a biblioteca.")}else setFeedback(body.error||"Falha ao enviar imagem.");setUploading(false);if(fileRef.current)fileRef.current.value=""}
  async function patch(item:MediaAsset,changes:Record<string,string>){const response=await fetch(withBasePath(`/api/admin/media/${item.id}`),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(changes)}),body=await response.json();if(response.ok){setItems(current=>current.map(record=>record.id===item.id?body:record));setFeedback("Imagem atualizada.")}else setFeedback(body.error||"Falha ao atualizar.")}
  async function rename(item:MediaAsset){const name=window.prompt("Novo nome do arquivo",item.filename);if(name&&name!==item.filename)await patch(item,{newName:name})}
  async function remove(item:MediaAsset){if(!window.confirm(`Excluir “${item.filename}”? URLs que usam este arquivo deixarão de funcionar.`))return;const response=await fetch(withBasePath(`/api/admin/media/${item.id}`),{method:"DELETE"});if(response.ok){setItems(current=>current.filter(record=>record.id!==item.id));setFeedback("Imagem excluída.")}else setFeedback("Não foi possível excluir a imagem.")}
  async function copy(url:string){await navigator.clipboard.writeText(url);setFeedback("URL copiada para a área de transferência.")}
  return <><div className="admin-toolbar"><div className="admin-toolbar-search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar por nome ou texto alternativo..."/></div><select value={type} onChange={event=>setType(event.target.value as MediaType|"all")}><option value="all">Todos os tipos</option>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="admin-primary-button" disabled={uploading} onClick={()=>fileRef.current?.click()}><Upload size={14}/>{uploading?"Enviando...":"Enviar imagem"}</button><input ref={fileRef} hidden type="file" accept="image/*" onChange={event=>upload(event.target.files?.[0])}/></div>{feedback&&<div className="admin-feedback">{feedback}</div>}<div className="admin-media-grid">{visible.map(item=><article className="admin-media-card" key={item.id}><div className="admin-media-preview"><Image src={item.url} alt={item.altText||item.filename} fill sizes="240px" unoptimized/></div><div className="admin-media-body"><b title={item.filename}>{item.filename}</b><small>{formatSize(item.size)}</small><label>Tipo<select value={item.type} onChange={event=>patch(item,{type:event.target.value})}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Alt text<input defaultValue={item.altText} onBlur={event=>event.target.value!==item.altText&&patch(item,{altText:event.target.value})}/></label><div className="admin-media-actions"><button onClick={()=>copy(item.url)} title="Copiar URL"><Clipboard size={13}/></button><button onClick={()=>rename(item)} title="Renomear"><Pencil size={13}/></button><button className="danger" onClick={()=>remove(item)} title="Excluir"><Trash2 size={13}/></button></div></div></article>)}{visible.length===0&&<div className="admin-empty admin-media-empty"><ImagePlus size={30}/><h2>Nenhuma imagem</h2><p>Envie o primeiro arquivo ou altere os filtros.</p></div>}</div></>
}
const formatSize=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;


