"use client";
import type { SeoSettings } from "@/types/admin";
import { useId } from "react";
import { useConfigEditor } from "./use-config-editor";
import { SaveBar } from "./save-bar";

export function SeoForm({initial}:{initial:SeoSettings}){
  const{data,setData,state,message,save}=useConfigEditor(initial,"/api/admin/seo");
  const field=(key:keyof SeoSettings,value:string)=>setData({...data,[key]:value});
  return <div className="admin-form"><details className="admin-section" open><summary>Metadados padrão</summary><div className="admin-section-body"><div className="admin-fields"><Field full label="Meta title padrão" value={data.defaultTitle} onChange={(v)=>field("defaultTitle",v)} hint={`${data.defaultTitle.length}/60 caracteres`}/><Field full textarea label="Meta description padrão" value={data.defaultDescription} onChange={(v)=>field("defaultDescription",v)} hint={`${data.defaultDescription.length}/160 caracteres`}/><Field full label="Keywords padrão" value={data.defaultKeywords.join(", ")} onChange={(v)=>setData({...data,defaultKeywords:v.split(",").map((item)=>item.trim()).filter(Boolean)})} hint="Separe por vírgulas; páginas específicas mantêm seus próprios termos."/><Field label="Imagem Open Graph padrão" value={data.defaultOgImage} onChange={(v)=>field("defaultOgImage",v)}/><Field label="Canonical base URL" type="url" value={data.canonicalBaseUrl} onChange={(v)=>field("canonicalBaseUrl",v)}/></div></div></details><details className="admin-section" open><summary>Indexação e rastreamento</summary><div className="admin-section-body"><div className="admin-fields"><label className="admin-check"><input type="checkbox" checked={data.robotsEnabled} onChange={(e)=>setData({...data,robotsEnabled:e.target.checked})}/>Permitir indexação no robots.txt</label><label className="admin-check"><input type="checkbox" checked={data.sitemapEnabled} onChange={(e)=>setData({...data,sitemapEnabled:e.target.checked})}/>Publicar referência ao sitemap</label><Field label="Google Analytics" value={data.googleAnalyticsId} onChange={(v)=>field("googleAnalyticsId",v)} hint="Ex.: G-XXXXXXXXXX"/><Field label="Google Tag Manager" value={data.googleTagManagerId} onChange={(v)=>field("googleTagManagerId",v)} hint="Ex.: GTM-XXXXXXX"/><Field label="Meta Pixel" value={data.metaPixelId} onChange={(v)=>field("metaPixelId",v)}/><Field label="LinkedIn Insight Tag" value={data.linkedinPartnerId} onChange={(v)=>field("linkedinPartnerId",v)}/></div></div></details><details className="admin-section"><summary>Schema Organization</summary><div className="admin-section-body"><div className="admin-fields"><Field label="Nome da empresa" value={data.organization.name} onChange={(v)=>setData({...data,organization:{...data.organization,name:v}})}/><Field label="URL da empresa" value={data.organization.url} onChange={(v)=>setData({...data,organization:{...data.organization,url:v}})}/><Field label="Logo da empresa" value={data.organization.logo} onChange={(v)=>setData({...data,organization:{...data.organization,logo:v}})}/><Field full textarea label="Descrição da empresa" value={data.organization.description} onChange={(v)=>setData({...data,organization:{...data.organization,description:v}})}/></div></div></details><SaveBar state={state} message={message} onSave={save}/></div>
}
function Field({label,value,onChange,type="text",textarea=false,full=false,hint}:{label:string;value:string;onChange:(value:string)=>void;type?:string;textarea?:boolean;full?:boolean;hint?:string}){const id=useId();return <div className={`admin-field ${full?"admin-field-full":""}`}><label htmlFor={id}>{label}</label>{textarea?<textarea id={id} value={value} onChange={(e)=>onChange(e.target.value)}/>:<input id={id} type={type} value={value} onChange={(e)=>onChange(e.target.value)}/>} {hint&&<small>{hint}</small>}</div>}
