"use client";
import type { PortalSettings } from "@/types/admin";
import { useId } from "react";
import { useConfigEditor } from "./use-config-editor";
import { SaveBar } from "./save-bar";

export function SettingsForm({initial}:{initial:PortalSettings}){
  const{data,setData,state,message,save}=useConfigEditor(initial,"/api/admin/settings");
  const field=(key:keyof PortalSettings,value:string)=>setData({...data,[key]:value});
  return <div className="admin-form"><details className="admin-section" open><summary>Identidade e contato</summary><div className="admin-section-body"><div className="admin-fields">
    <Field label="Nome do portal" value={data.portalName} onChange={(v)=>field("portalName",v)}/><Field label="Subtítulo" value={data.subtitle} onChange={(v)=>field("subtitle",v)}/><Field label="Slogan" value={data.slogan} onChange={(v)=>field("slogan",v)}/><Field label="URL principal" type="url" value={data.primaryUrl} onChange={(v)=>field("primaryUrl",v)}/><Field label="E-mail de contato" type="email" value={data.contactEmail} onChange={(v)=>field("contactEmail",v)}/><Field label="Telefone institucional" value={data.phone} onChange={(v)=>field("phone",v)}/><Field full textarea label="Descrição institucional" value={data.institutionalDescription} onChange={(v)=>field("institutionalDescription",v)}/>
  </div></div></details><details className="admin-section" open><summary>WhatsApp comercial</summary><div className="admin-section-body"><div className="admin-fields">
    <label className="admin-check"><input type="checkbox" checked={data.whatsapp.enabled} onChange={(e)=>setData({...data,whatsapp:{...data.whatsapp,enabled:e.target.checked}})}/>Canal habilitado (exibe o CTA &ldquo;Falar com um especialista&rdquo; via WhatsApp)</label>
    <Field label="Número exibido" value={data.whatsapp.displayNumber} onChange={(v)=>setData({...data,whatsapp:{...data.whatsapp,displayNumber:v}})} hint="Formato de exibição, ex: (55) 9663-4475"/>
    <Field label="Número normalizado" value={data.whatsapp.normalizedNumber} onChange={(v)=>setData({...data,whatsapp:{...data.whatsapp,normalizedNumber:v}})} hint="Apenas dígitos, com código do país. Ex: 555596634475"/>
    <Field full textarea label="Mensagem inicial" value={data.whatsapp.defaultMessage} onChange={(v)=>setData({...data,whatsapp:{...data.whatsapp,defaultMessage:v}})} hint="Preenche o campo de mensagem no WhatsApp — o visitante ainda precisa enviar manualmente."/>
  </div></div></details><details className="admin-section" open><summary>Header e navegação</summary><div className="admin-section-body"><div className="admin-fields"><Field label="Texto do botão do header" value={data.headerButton.label} onChange={(v)=>setData({...data,headerButton:{...data.headerButton,label:v}})}/><Field label="Link do botão do header" value={data.headerButton.url} onChange={(v)=>setData({...data,headerButton:{...data.headerButton,url:v}})}/><div className="admin-field admin-field-full"><label>Links principais do menu</label><LinkRows links={data.menuLinks} onChange={(menuLinks)=>setData({...data,menuLinks})}/></div></div></div></details><details className="admin-section"><summary>Rodapé</summary><div className="admin-section-body"><div className="admin-fields"><Field label="Texto legal" value={data.footerText} onChange={(v)=>field("footerText",v)}/><Field label="Nota do rodapé" value={data.footerNote} onChange={(v)=>field("footerNote",v)}/>{data.footerColumns.map((column,columnIndex)=><div className="admin-field admin-field-full" key={`${column.title}-${columnIndex}`}><Field label={`Título da coluna ${columnIndex+1}`} value={column.title} onChange={(v)=>setData({...data,footerColumns:data.footerColumns.map((c,i)=>i===columnIndex?{...c,title:v}:c)})}/><label>Links</label><LinkRows links={column.links} onChange={(links)=>setData({...data,footerColumns:data.footerColumns.map((c,i)=>i===columnIndex?{...c,links}:c)})}/></div>)}</div></div></details><details className="admin-section"><summary>Redes sociais</summary><div className="admin-section-body"><div className="admin-fields"><div className="admin-field admin-field-full"><div className="admin-array">{data.socialLinks.map((social,index)=><div className="admin-array-row" key={`${social.network}-${index}`}><input aria-label="Rede social" value={social.network} onChange={(e)=>setData({...data,socialLinks:data.socialLinks.map((s,i)=>i===index?{...s,network:e.target.value,label:e.target.value}:s)})}/><input aria-label="URL da rede" value={social.url} onChange={(e)=>setData({...data,socialLinks:data.socialLinks.map((s,i)=>i===index?{...s,url:e.target.value}:s)})}/><button type="button" onClick={()=>setData({...data,socialLinks:data.socialLinks.filter((_,i)=>i!==index)})}>Remover</button></div>)}<button className="admin-add" type="button" onClick={()=>setData({...data,socialLinks:[...data.socialLinks,{network:"Nova rede",label:"Nova rede",url:"https://"}]})}>+ Adicionar rede</button></div></div></div></div></details><SaveBar state={state} message={message} onSave={save}/></div>
}

function Field({label,value,onChange,type="text",textarea=false,full=false,hint}:{label:string;value:string;onChange:(value:string)=>void;type?:string;textarea?:boolean;full?:boolean;hint?:string}){const id=useId();return <div className={`admin-field ${full?"admin-field-full":""}`}><label htmlFor={id}>{label}</label>{textarea?<textarea id={id} value={value} onChange={(e)=>onChange(e.target.value)}/>:<input id={id} type={type} value={value} onChange={(e)=>onChange(e.target.value)}/>}{hint&&<small>{hint}</small>}</div>}
function LinkRows({links,onChange}:{links:Array<{label:string;url:string}>;onChange:(links:Array<{label:string;url:string}>)=>void}){return <div className="admin-array">{links.map((link,index)=><div className="admin-array-row" key={`${link.label}-${index}`}><input aria-label="Texto do link" value={link.label} onChange={(e)=>onChange(links.map((item,i)=>i===index?{...item,label:e.target.value}:item))}/><input aria-label="Destino do link" value={link.url} onChange={(e)=>onChange(links.map((item,i)=>i===index?{...item,url:e.target.value}:item))}/><button type="button" onClick={()=>onChange(links.filter((_,i)=>i!==index))}>Remover</button></div>)}<button className="admin-add" type="button" onClick={()=>onChange([...links,{label:"Novo link",url:"/"}])}>+ Adicionar link</button></div>}
