import { promises as fs } from "node:fs";import path from "node:path";import type { BackupPayload } from "@/types/operations";
const files=["settings","branding","seo","home","posts","educational-articles","categories","authors","tags","segments","events","media","leads","logs"] as const;const directory=path.join(process.cwd(),"src","content");
const objectFiles=new Set<string>(["settings","branding","seo","home"]);const arrayFiles=new Set<string>(files.filter(name=>!objectFiles.has(name)));
function isPlainObject(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==="object"&&!Array.isArray(value)}
function validateBackup(payload:BackupPayload){if(payload?.version!==1||!isPlainObject(payload.data))throw new Error("Backup inválido ou incompatível.");for(const[name,value]of Object.entries(payload.data)){if(!files.includes(name as typeof files[number]))continue;if(objectFiles.has(name)&&!isPlainObject(value))throw new Error(`A coleção ${name} deve ser um objeto.`);if(arrayFiles.has(name)&&(!Array.isArray(value)||value.some(item=>!isPlainObject(item))))throw new Error(`A coleção ${name} deve ser uma lista de registros.`)}}
export async function exportBackup():Promise<BackupPayload>{const entries=await Promise.all(files.map(async name=>{const raw=await fs.readFile(path.join(directory,`${name}.json`),"utf8");return[name,JSON.parse(raw)] as const}));return{version:1,exportedAt:new Date().toISOString(),data:Object.fromEntries(entries)}}
export async function importBackup(payload:BackupPayload){validateBackup(payload);for(const name of files){if(!(name in payload.data))continue;const value=payload.data[name];if(value===undefined)continue;const destination=path.join(directory,`${name}.json`),temporary=`${destination}.${Date.now()}.tmp`;await fs.writeFile(temporary,`${JSON.stringify(value,null,2)}\n`,"utf8");await fs.rename(temporary,destination)}return true}
export const backupFiles=files;
export async function exportContentFile(name:string){if(!files.includes(name as typeof files[number]))throw new Error("Arquivo de conteúdo inválido.");return fs.readFile(path.join(directory,`${name}.json`),"utf8")}
